spring:
  application:
    name: payment-gateway
  http:
    client:
      connect-timeout: 2s
      read-timeout: 5s

server:
  port: 8090

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

payment:
  supported-currencies: EUR, GBP, USD

acquiring-bank:
  url: http://localhost:8080/payments